#define T_AND                            1
#define T_OR                             2
#define T_UNION                          3
#define T_EQ                             4
#define T_NE                             5
#define T_GT                             6
#define T_GE                             7
#define T_LT                             8
#define T_LE                             9
#define T_NOT                           10
#define T_LABEL                         11
#define T_ROOT                          12
#define T_THIS                          13
#define T_DOT                           14
#define T_WILDCARD                      15
#define T_BROPEN                        16
#define T_BRCLOSE                       17
#define T_BOOL                          18
#define T_NUMBER                        19
#define T_STRING                        20
#define T_POPEN                         21
#define T_PCLOSE                        22
